POST http://localhost:3000/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJlbWFpbCI6InRvYW52aXAxMjNAZ21haWwuYWFhY29tIiwiaWF0IjoxNzI3MDg2OTM1LCJleHAiOjE3MjcwOTA1MzUsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.BvQN_RCQCbQaBj2YvI62aU86rbNBCWhap6C0XGdEBEE
{
   "title" : "toan dep dai",
   "description": "description 1",
   "postType": "post",
   "slug": "toan-dep-dai-3334343-222-11",
   "status": "draft",
   "content": "test content",
   "publishOn": "2024-03-16T07:46:32+0000",
   "schema": "{\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }",
    "featureImgUrl": "http://localhost.com/images/image1.jpg",
   "tags": [1,3,4,5],
   "metaOptions": {
    "metaValue": "{\"sideBar\": true, \"footer\": true}"
   }
    
}